### ISSUE TITLE
publish to sonatype or bintray

### ISSUE THREAD

**Issue by antonkulaga** [jbytecode/rcaller#1]
Please, publish to either sonatype or bintray so people will be able to use your lib as dependency in sbt/maven/gradle

**Comment by jbytecode** [comment]
ok, would you like to join and make these stuff?

**Comment by paul150792** [comment]
if antonkulaga dosen't want to join, I'll do it today.

**Comment by jbytecode** [comment]
Ok  @paul150792, this job is yours. Lets do it.

@antonkulaga is also welcome for performing other stuff.

**Comment by jbytecode** [comment]
Was this issue totaly solved and tested?
If yes, we can close it.

**Comment by paul150792** [comment]
Yes, it's solved and tested.
and with each release I will update it on the sonatype server

**Comment by jbytecode** [comment]
Thank you Paul
