### ISSUE TITLE
problem with parse in utf-8

### ISSUE THREAD

**Issue by stevensotelo** [jbytecode/rcaller#2]
Your code has problems when a temp file "Routput" has special character with accents. I found this error and I want to contribute to fix it. can you invite me to contribute to this repository?

**Comment by jbytecode** [comment]
Okay. Welcome!

**Comment by jbytecode** [comment]
Hi Steven,
After adding your code and getting all tests passed we can close this issue. 
Thank you in advance

**Comment by stevensotelo** [comment]
Thanks to you Satman, It was upload already.

**Comment by jbytecode** [comment]
Thank you for your contribution.
Stay in touch

**Comment by jbytecode** [comment]
In MacOs, there is a problem about UTF8 tests. The error log is

`Running com.github.rcaller.UTF8Test

Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.562 sec <<< FAILURE!

Utf8CharactersTest(com.github.rcaller.UTF8Test)  Time elapsed: 0.304 sec  <<< FAILURE!

java.lang.AssertionError: 
	at org.junit.Assert.fail(Assert.java:91)
	at org.junit.Assert.assertTrue(Assert.java:43)
	at org.junit.Assert.assertTrue(Assert.java:54)
	at com.github.rcaller.UTF8Test.Utf8CharactersTest(UTF8Test.java:33)
	...
``

any idea?

**Comment by jbytecode** [comment]
thank you @Kopilov , will try later.

**Comment by jbytecode** [comment]
@Kopilov when arrow is enabled, tests are not passed with message

`java.lang.NoClassDefFoundError: Could not initialize class org.apache.arrow.memory.util.MemoryUtil`

using maven. what is the problem with this?

**Comment by Kopilov** [comment]
@jbytecode if you are running tests as tests (in the corresponding scope), it should work (if classloading is not broken in MacOS again) and works for me. My `mvn --version` is
```
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 11.0.11, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: ru_RU, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-80-generic", arch: "amd64", family: "unix"
```

If you are running test as a regular main function (such as benchmark), remove `<scope>test</scope>` and `<scope>provided</scope>` tags from the pom file or use separate project/module. Scope tags were added for the dependency to be optional.

**Comment by Kopilov** [comment]
If anything has happened with transitive dependencies loading, try to add https://mvnrepository.com/artifact/org.apache.arrow/arrow-memory-core/5.0.0 directly, it contains the problematic class

**Comment by Kopilov** [comment]
@jbytecode if the error is reasoned by class initializing itself and not by finding, try to replace arrow-memory-netty dependency (which is also an optional implementation) with https://mvnrepository.com/artifact/org.apache.arrow/arrow-memory-unsafe/5.0.0

**Comment by jbytecode** [comment]
couldn't it be implemented in such way that we can simply do mvn test?

**Comment by Kopilov** [comment]
`mvn test` should work, without any changes. If it does not, please, show me the full `mvn test` and `mvn --version` output.

Here is mine: https://gist.github.com/Kopilov/2bf2de45b946091656ce200d39473291 (I have added some trace output to clarify that Arrow is used)

**Comment by Kopilov** [comment]
@jbytecode is NoClassDefFoundError throwed on MacOS only?

**Comment by jbytecode** [comment]
@Kopilov didnt try in linux yet

**Comment by jbytecode** [comment]
runs in both Linux and MacOs.
