### ISSUE TITLE
Broken Link to Official Publication?

### ISSUE THREAD

**Issue by wongjoel** [jbytecode/rcaller#20]
The Link to the official publication currently points to 
'''
http://www.sciencedomain.org/download.php?f=Satman4152014BJMCS10902_1.pdf&aid=4838&type=a
'''
But this leads to a "Sorry file does not exist." error

I believe the correct link (well, at least one that should be more permanent) should be
'''
https://doi.org/10.9734/BJMCS/2014/10902
'''

Thanks for your work,

**Comment by jbytecode** [comment]
Updated. Thank you!

**Comment by wongjoel** [comment]
Thanks
