### ISSUE TITLE
NullPointerException on Windows if R not installed in C:\Program Files

### ISSUE THREAD

**Issue by wongjoel** [jbytecode/rcaller#22]
When running a 64-bit JVM on Windows, with only a 32-bit version of R installed, the R version detection code in Globals.java returns a null pointer exception in line 65. The following code seems to be the problem:

```
...
static {
        if (isWindows()) {
            String programFiles = System.getenv("ProgramFiles");
            if (programFiles == null) {
                programFiles = "C:\\Program Files";
            }
            File rBase = new File(programFiles, "R");
            File[] rVersions = rBase.listFiles(new FileFilter() {
                @Override
                public boolean accept(File pathname) {
                    return pathname.isDirectory() && pathname.getName().startsWith("R-");
                }
            });
Arrays.sort(rVersions);
...
```
When called from a 64-bit JVM, `System.getenv("ProgramFiles");` returns "C:\Program Files", which is a problem when R is not installed under "C:\Program Files" (e.g. if R was installed under "C:\Program Files (x86)" instead).

I'm not too sure of the best way of fixing this - short term, maybe adding a check for null on rVersions before calling Arrays.sort could at least avoid the nullPointerException being thrown?

**Comment by thetg** [comment]
Hi,
I have a very similar problem.
My R is installed on another drive (E:).
When I try to run any example, the line
`RCaller caller = RCaller.create(); `
produces a NullPointerException at `Arrays.sort(rVersions);`
I tried to change the paths at the top of Globals.java manually, but it doesn't work.
Is there a proper way to tell RCaller where my R is located?
Any hint would be very appreciated.

**Comment by paulcurcean** [comment]
I added now methods in `com.github.rcaller.util.Globals` for defining the paths. The changes are pushed, but not available as maven pacakge.

**Comment by wongjoel** [comment]
Thanks for adding the methods in `com.github.rcaller.util.Globals` . I cloned the repo and built a local copy to test. Unfortunately, the static initialization block still runs and throws the mentioned `NullPointerException` before it is possible to call any of these methods, so the issue isn't resolved yet.

Personally, I would change the static initialization block into a static function to avoid throwing the `NullPointerException` as soon as the class is loaded, but I'm not sure if that has any implications on the rest of the code.

Thanks again for your work, it is much appreciated, especially when trying to resolve this issue.

**Comment by paulcurcean** [comment]
If you want, you can change the code as you wish and then make a pull request. 
And if everything passes, I can merge it and after that publish a jar to maven. 3.0.1

**Comment by paulcurcean** [comment]
I think that this issue can be closed now.
