### ISSUE TITLE
New NullPointerException whith R installed on E:

### ISSUE THREAD

**Issue by thetg** [jbytecode/rcaller#25]
Hi,
I followed the discussion in _NullPointerException on Windows if R not installed in C:\Program Files #22_ closely as I had the same problem, and was very happy to see the fast presentation of a solution.
So I got the updated version, but unfortunately RCaller is still not working for me.
The simple code
```
import com.github.rcaller.rstuff.RCaller;
import com.github.rcaller.util.Globals;

public class Test{
	public static void main( String[] args ){
		Globals.setRPaths( "E:\\R\\R-3.1.1\\bin\\Rscript.exe" , "E:\\R\\R-3.1.1\\bin\\R.exe" );
		RCaller caller = RCaller.create();
	}
}
```
gives the following Exception:
```
Exception in thread "main" java.lang.NullPointerException
	at java.io.Reader.<init>(Unknown Source)
	at java.io.InputStreamReader.<init>(Unknown Source)
	at com.github.rcaller.rstuff.RCode.clear(RCode.java:77)
	at com.github.rcaller.rstuff.RCode.create(RCode.java:52)
	at com.github.rcaller.rstuff.RCaller.create(RCaller.java:83)
	at Test.main(Test.java:7)
```
Interestingly, when I delete the `Globals.setRPaths(...)` line, the Exception stays the same.
I also tried to install a new version of R in C:\Program Files, but still got the same problem.
As lines 76 and 77 of RCode.class are
```
InputStream is = this.getClass().getClassLoader().getResourceAsStream("runiversal.r");
InputStreamReader inputStreamReader = new InputStreamReader(is);
```
i double checked the installation of Runiversal and it is in E:\R\R-3.1.1\library\Runiversal as I guess it should be.
Thanks for reading this, any hint would be appreciated.

**Comment by paulcurcean** [comment]
Strange error you got there, it seems that there's a problem with the classLoader, because it's not able to find the needed resource.

Due to the fact that I'm not a Windows user and Jenkins is on Linux, I won't be able to reproduce your error.

Hopefully a Windows user will be able to help.

**Comment by wongjoel** [comment]
I'm not sure how to reproduce the problem either. How are you adding RCaller to the classpath? And would it be possible for you to step through the code to determine which part of line 77 is returns null first?

**Comment by thetg** [comment]
@wongjoel had the right idea and I could fix my mistake.
I created a new .jar with the updated Globals.class and missed to include "runiversal.r".
After creating the .jar properly it now works fine.
I'm happy that I now can start to explore RCaller.
Thank you so much for your answers.
