### ISSUE TITLE
Exception in thread "main" java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by bclarens** [jbytecode/rcaller#32]
I keep getting this error
![image](https://user-images.githubusercontent.com/23650572/34773643-69863af4-f647-11e7-8191-62b335bb3509.png)
everytime I run the Main.java example found on the repo. A help would be great. Thanks!
Btw, I added the rcaller 3.1 snapshot jar in the libraries.

**Comment by tomgrille** [comment]
You need to tell RCaller where your executables are. So add something like
```
String pathToRScript = "E:\\R\\R-3.5.1\\bin\\Rscript.exe";
String pathToR = "E:\\R\\R-3.5.1\\bin\\R.exe";
RCallerOptions options = RCallerOptions.create(pathToRScript, pathToR, FailurePolicy.RETRY_1, 3000l, 100l, RProcessStartUpOptions.create());
RCaller caller = RCaller.create(options);
```

**Comment by jbytecode** [comment]
@bclarens @tomgrille is this issue solved?
