### ISSUE TITLE
Closing plot window closes parent application too.

### ISSUE THREAD

**Issue by Georim** [jbytecode/rcaller#33]
Hello.
I generate plots using RCaller. The plots looks fine. But when user close plot window, parent window also getting close. 
It seems to me, that parent window should not be close in the case.

I suppose that the reason of the behavior is 

  public RPlotViewer(ImageIcon img) {
    this.img = img;
    this.setSize(img.getIconWidth() + 20, img.getIconHeight() + 60);
    **this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);**
    this.setTitle("RCaller 2.0 - Generated Plot");
    repaint();
  }

I think to close plot window, without closing all application **JFrame.DISPOSE_ON_CLOSE**
should be used.

**Comment by jbytecode** [comment]
ok, done.
Thanks.
