### ISSUE TITLE
maven example gives 401 Unauthorized

### ISSUE THREAD

**Issue by ushulau** [jbytecode/rcaller#4]
Failed to collect dependencies at org.expr.rcaller:RCaller:jar:2.6.0.3: Failed to read artifact descriptor for org.expr.rcaller:RCaller
:jar:2.6.0.3: Could not transfer artifact org.expr.rcaller:RCaller:pom:2.6.0.3 from/to sonatype-nexus-snapshots (https://oss.sonatype.org/service/local/staging/deploy/maven2/): Not authorized , ReasonPhrase:Unauthorized. -> [Help 1]

Could this be published somewhere with public access?

**Comment by carlgzuora** [comment]
I'm getting the same error

**Comment by Hoeze** [comment]
+1
Would be great if this could be fixed

**Comment by paulcurcean** [comment]
It should work now. The Rcaller was published to maven central:
http://mvnrepository.com/artifact/com.github.jbytecode/RCaller/2.8
