### ISSUE TITLE
Manuscript submission

### ISSUE THREAD

**Issue by jbytecode** [jbytecode/rcaller#42]
Hi friends,

I have prepared a manuscript and submitted to Journal of Open Source Software that presents RCaller. Since you all have valuable contributions, the dear editor @mikldk kindly asked me to ask if you would like to participate in this article. Here is the pre-review link: [https://github.com/openjournals/joss-reviews/issues/2600](https://github.com/openjournals/joss-reviews/issues/2600)

If your answer is yes, please add your contributions and your name to the paper hosted in our RCaller repository ([the paper directory](https://github.com/jbytecode/rcaller/tree/master/paper)). If your answer is no, please make an explanation. 

Best wishes.

@paulcurcean 
@mbatchkarov ✓ 
@Kopilov ✓
@dieresys ✓
@wongjoel ✓
@ksfx ✓
@waffle-iron 
@stevensotelo 
@gitter-badger 
@edineipiovesan 
@sjcetx ✓

**Comment by wongjoel** [comment]
Well, my contributions were to help out with making the R path on Windows more flexible. I don't think that makes me a major committer, so I'm happy with just being in the Acknowledgement section.

**Comment by ksfx** [comment]
I only made tiny contributions. I'm very happy with the Acknowledgement section

**Comment by jbytecode** [comment]
@wongjoel @ksfx  okay, minor changes and contributions are still important and valuable, thank you. I am sorry for the belated invitation.

**Comment by Kopilov** [comment]
I have added StopRCallerAsync method that allows to kill long or freezed calculation from separate thread (actually, for timeout feature asked by customer in my my project https://github.com/Kopilov/RCallerService)
In the process "TODO checking file length is wrong" had been fixed.

@jbytecode, would you like me to commit something to https://github.com/jbytecode/rcaller/tree/master/paper directory?
I do not have any experience with JOSS publishing, sorry

**Comment by jbytecode** [comment]
@Kopilov Since you have contributions to RCaller, you have rights to be a co-author in the manuscript. If you want to be a part of this manuscript, you can make contributions to the md file in the repo and add your name. I can review your changes and try to bring it to the shape required by the journal. JOSS has a well-defined list of publishing rules, so you can carefully read it. The submitted paper is a good starting point.

**Comment by jbytecode** [comment]
@Kopilov as an opinion, maybe you can refer to RCallerService, so we can show up that the RCaller is not just a stand-alone library, it is used in another libraries as a base.

**Comment by jbytecode** [comment]
We have a new issue here for possible questions and discussions for those who accept to participate.
 
[https://github.com/jbytecode/rcaller/issues/43](https://github.com/jbytecode/rcaller/issues/43)

**Comment by jbytecode** [comment]
Unresponsive friends, come on, return a positive or negative answer. Let's stand on the shoulders of giants.

**Comment by dieresys** [comment]
I only made tiny contributions. I'm very happy with the Acknowledgement section.
Thanks!

**Comment by mbatchkarov** [comment]
Same

**Comment by jbytecode** [comment]
@waffle-iron @stevensotelo @gitter-badger @edineipiovesan 

I apologize for bothering you over and over again, but it would be great if you could give an answer.

**Comment by jbytecode** [comment]
@ sjcetx welcome to RCaller. Since you are a new contributor, please read the entire issue and give a response. Thank you in advance. If your answer is no, please write your name so we can put it in the Acknowledge section.

**Comment by sjcetx** [comment]
As my contributions were minimal being in the acknowledgements is more than enough.
Thanks,
Simon Carter

**Comment by jbytecode** [comment]
> As my contributions were minimal being in the acknowledgements is more than enough.
> Thanks,
> Simon Carter

okay, I added your name in the  acknowledgements part of manuscript @sjcetx . Keep with us.

**Comment by edineipiovesan** [comment]
I fixed some charset issues and added default path for R in macOS. Pretty tiny changes, so I'll be happy with the Acknowledgement section.
Thanks,
Edinei Piovesan

**Comment by jbytecode** [comment]
> I fixed some charset issues and added default path for R in macOS. Pretty tiny changes, so I'll be happy with the Acknowledgement section.
> Thanks,
> Edinei Piovesan

thank you very much for being a part of the project
