### ISSUE TITLE
Contributions to manuscript prepared for JOSS

### ISSUE THREAD

**Issue by jbytecode** [jbytecode/rcaller#43]
We can discuss possible contributions to the manuscript here. @Kopilov will you participate? I can help to you if you have any confusions.

**Comment by Kopilov** [comment]
@jbytecode I am ready, thanks!

At first, is orcid necessary to add me to the authors list? If yes, how can I get it?

My single scientific work is xAPI translation to russian (started as https://github.com/Kopilov/xAPI-Spec/blob/translate_ru/xAPI_ru.md, published as http://books.ifmo.ru/file/pdf/1772.pdf)

**Comment by jbytecode** [comment]
Yes you can take a new researcher id. Please, open the page https://orcid.org/ and register. 

No previous scientific work is required, you have contributions in RCaller, that is enough.

**Comment by Kopilov** [comment]
Commited to https://github.com/Kopilov/rcaller/blob/paper/paper/paper.md
The table is not displayed as a table anymore :( 
My patch is https://github.com/Kopilov/rcaller/commit/a8a2cbbc4f03d6dfe3750577e7007377a524ab5b

**Comment by Kopilov** [comment]
Nevertheless, what should be put in "affiliation" field?

**Comment by jbytecode** [comment]
it is where you are working on.

you can edit like this:

authors:
  - name: Mehmet Hakan Satman
    orcid: 0000-0002-9402-1982
    affiliation: 1
  - name: Kopilov Aleksandr
    orcid: 0000-0002-8223-2168
    affiliation: 2
affiliations:
 - name: Department of Econometrics, Istanbul University
   index: 1
 - name: Where you work on
   index: 2

**Comment by jbytecode** [comment]
and this is the md to pdf compiler, you can control your file here

[https://whedon.theoj.org/](https://whedon.theoj.org/)

**Comment by jbytecode** [comment]
any problem?  @Kopilov

**Comment by Kopilov** [comment]
@jbytecode just returned from lunch, will try now. Thanks!

**Comment by jbytecode** [comment]
I have commented on your commits, have you seen them @Kopilov

**Comment by Kopilov** [comment]
@jbytecode yes, thanks!
I have fixed the last paragraph, now will try to make correct reference by the bibtex file

**Comment by jbytecode** [comment]
as a note for all contributers: 

when a reference is used like [@SomeCitationsHereAsAKeyword] in md file, an entry should be placed like

@misc{SomeCitationsHereAsAKeyword,
      title        = "Pluto: The 'Other' Red Planet",
      author       = "{NASA}",
      howpublished = "\url{https://www.nasa.gov/nh/pluto-the-other-red-planet}",
      year         = 2015,
      note         = "Accessed: 2018-12-06"
    }

in bibtex file. If the entry type is a paper, a doi number is required.

**Comment by jbytecode** [comment]
@Kopilov your changes seem to be okay, md file compiles perfectly. When you have done, you can submit a pull request.

**Comment by jbytecode** [comment]
@Kopilov  here is the review link of our paper

https://github.com/openjournals/joss-reviews/issues/2722

**Comment by nthomasCUBE** [comment]
Hi,

I quess in the example from your manuscript, you have defined "en" but then use "engine" (e.g. engine.put("a",a)
like here:

		ScriptEngineManager manager=new ScriptEngineManager();
		ScriptEngine **en**=manager.getEngineByName("RCaller");
		
		System.out.println("JA");
		
		try {
			double[] a=new double[] {19.0, 17.0, 23.0};
			**en**.put("a",a);
			**en**.eval("sortedA <- sort(a)");
			double[] result=(double[])en.get("sortedA");
			System.out.println(result[0]);
		} catch (ScriptException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}


br

**Comment by jbytecode** [comment]
@Kopilov In the later stages of manuscript review, your city and country may be required. Please write here so I can add it if they asked me to add.

**Comment by Kopilov** [comment]
@jbytecode My country is Russian Federation and city is Saint Petersburg

**Comment by jbytecode** [comment]
@Kopilov the reviewing process has been finished. I am closing this issue. thank you!
