### ISSUE TITLE
 [JOSS REVIEW] Suggestion for Documentation

### ISSUE THREAD

**Issue by xin-huang** [jbytecode/rcaller#55]
This is a part of the JOSS review (openjournals/joss-reviews#2722)

1. It is not clear that who is the target audience, I suggest the authors make it clear as the review checklist suggests.
2. For the installation, the version of RCaller in the Maven dependency code in [the manual](https://raw.githubusercontent.com/jbytecode/rcaller/master/doc/rcaller3/rcaller3.pdf) is 3.0, whereas it is 2.8 in the README.md. This makes me confused which version I should use. I also feel that the instruction for installation in the manual is better than that in the README.md. It tells readers more clearly that there are two approaches to install RCaller, one is through Maven, the other is by downloading the jar file and add it into the classpath. I suggest the authors also replace the instruction for installation in the README.md by the instruction in the manual. 
3. It is not clear that what are the dependencies for RCaller, at least, the authors should state which version of Java is required for RCaller. Or does RCaller support all the versions of Java? Based on my simple test, it looks like RCaller does not support Java 1.5. Besides, RCaller is an interface between R and Java, therefore, another dependency should be R at least. Does RCaller support all the versions of R? In Page 3 of the manual, the second paragraph of the Setup and Installation section, it says that all the dependencies including the libraries that RCaller imports are downloaded. What are the dependencies that RCaller imports and downloads? I suggest the authors make the versions of Java and R as well as the dependencies clear in the documentation. Also, I suggest the authors list the dependencies in the README.md for the RCaller repo, so that users do not need to search for them in the long manual.
4. The authors provide a lot of [examples](https://github.com/jbytecode/rcaller/tree/master/RCaller/src/main/java/examples), but it is not clear that what the purpose for each example is. For example, the authors only named the examples such as Example2.java, Example3.java and so on. It is difficult for users to figure out what the example is used for by themselves. I suggest the authors rename the example files and add annotation into the examples for users to have a better understanding. Also, I suggest the authors list their examples in the README.md, so that users can quickly find out the examples they need instead of searching examples one by one.
The authors also provided several code examples in [the manual](https://raw.githubusercontent.com/jbytecode/rcaller/master/doc/rcaller3/rcaller3.pdf), e.g., Listing 3. However, after copying these codes and pasting them into the IDE, these codes became weird and I have to reformat them. Therefore, I suggest the authors use more simple style, e.g. remove the line number and use plain text, for their code examples in the manual, so that users can copy and test the codes more easily.
5. API method documents are missing. The authors should add them into the repo as the review checklist suggests.
6. The community guidelines are missing. The authors should add them into the README.md as the review checklist suggests.

**Comment by jbytecode** [comment]
Dear viewer @xin-huang 

1. "Who uses RCaller?" section added in [README.md](https://github.com/jbytecode/rcaller#who-uses-rcaller) 

2. Instructions for installing and building is added in [README.md](https://github.com/jbytecode/rcaller#building-and-installing-rcaller)

3. Dependencies section added in [README.md](https://github.com/jbytecode/rcaller#dependencies). RCaller compiles with JDK1.8 but I don't remember what was the oldest revision of R was tested. There is a version history of R [here](https://github.com/r-hub/rversions) and I think v2.0.0 or higher is enough. (Today v4.x.x is current).
However, we don't use any version specific functionality of R. This is explained in the section.

4. The manual LaTeX file is updated, a new pdf is compiled, line numbers removed for easy copy-paste stuff. pdf is [here](https://github.com/jbytecode/rcaller/blob/master/doc/rcaller3/rcaller3.pdf).
Examples are refactored by means of file names, descriptions and comments. Some examples are suitable to ship in a single file so the number of examples is changed. A selected subset of examples are presented in [README.md](https://github.com/jbytecode/rcaller#usage)

5. JavaDocs are compiled and hosted [here](https://github.com/jbytecode/rcaller/tree/master/RCaller/target/apidocs).

6. We have [a page](https://github.com/jbytecode/rcaller/blob/master/CONTRIBUTING.md) for newcomers. It is added to [README.md](https://github.com/jbytecode/rcaller/blob/master/CONTRIBUTING.md). 


I corrected & added & removed all the stuff you mentioned above. Please specify if there is anything I forgot or misunderstood.

Best regards.

**Comment by jbytecode** [comment]
Dear reviewer @xin-huang ,

Based on your comment 

> Besides, although the authors did not mention performance in the software paper, they discussed this issue in the manual. Therefore, I suggest the authors release their codes for the benchmark, so that users can verify the performance issue more easily.

in JOSS review page, I regret to state that the code we used in the benchmark is not available. If you find it really necessary to present time consumed by the API, I can replicate the simulations using the data generating process given in the manual paper. However this may have time.

Regards.

**Comment by xin-huang** [comment]
Thanks @jbytecode 
I think the changes in the documentation are good.
And please make your benchmark publicly available, then other people could reproduce your results.

**Comment by jbytecode** [comment]
Dear reviewer @xin-huang ,

As in the described in the manual paper, I wrote the simulation code from scratch, it is in [PassingArraysAndMatrices.java](scratch). Since it is parameterized, any size of vector and squared matrices can be tested as in the manual and descriptive statistics are reported like 


```
- Simulations started.
- Simulations finished. Calculating statistics:
       Min        Max       Mean   Std.Dev.     Median        Mad
 77.000000 445.000000  90.198000  13.782843  89.000000   7.413000
```

  The number of simulations and the number of vector sizes can be changed by the tester. If the number of simulations is reduced then the variance is increased however giving big simulation counts takes more time. 

Please tell me if there is anything wrong or missing.

Best regards.

**Comment by xin-huang** [comment]
Hi @jbytecode 

Because you already have the codes, I think you just highlight it in the README.md, for example, make a link in the README.md to these codes, and let others know if they want to check the performance, they can look at these codes. Thanks.

**Comment by jbytecode** [comment]
Dear editor @xin-huang ,

This is mentioned in README.md file [here](https://github.com/jbytecode/rcaller/blob/master/README.md#benchmarks).

Regards.

**Comment by xin-huang** [comment]
Thanks @jbytecode 
It looks good
