### ISSUE TITLE
Rcaller and concurrency

### ISSUE THREAD

**Issue by mullon-ch** [jbytecode/rcaller#58]
I am trying to control the RCallerRunOnLine calls to rcaller and search the way to interrupt them when they result in too long computations. I am using the Java concurrent framework, which I don't know very well.

With the following program, 

```
import`_`` com.github.rcaller.rstuff.*;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.*;
import javafx.stage.Stage;
import java.util.List;
import java.util.concurrent.*;
import java.util.logging.Level;
import java.util.logging.Logger;

public class CallerApplication extends Application {

    public static void main(String[] args) { launch(args); }

    static RCaller caller;
    RCode code;
    ExecutorService executor;
    RunRCommand runRCommand;

    @Override
    public void start(Stage primaryStage) {
        // -----------------------------
        GridPane gridPane = new GridPane();
        Button stop = new Button("Stop");
        stop.setOnAction(e -> {
            caller.StopRCallerOnline();
            executor.shutdownNow();
        });
        gridPane.add(stop,0,0);
        Scene scene = new Scene(gridPane, 300, 300);
        primaryStage.setScene(scene);
        // -----------------------------
        executor = Executors.newFixedThreadPool(10);
        runRCommand = new RunRCommand();
        executor.execute(runRCommand);
        // -----------------------------
        primaryStage.show();
        // -----------------------------
    }

    void initR(){
        code = RCode.create();
        RCallerOptions rCallerOptions = RCallerOptions.create(
                "/usr/local/bin/Rscript",
                "/usr/local/bin/R", FailurePolicy.RETRY_5,
                9223372036854775807L,
                100L,
                RProcessStartUpOptions.create());
        caller = RCaller.create(code, rCallerOptions);
        code.clear();
        String  n = "10000"; 
        StringBuilder sb = new StringBuilder("");
        sb.append("for(j in 1:"+n+") { \n");
        sb.append("for(i in 1:"+n+") { u <- cos( (i+j) *pi/180) } \n");
        sb.append("} \n");
        sb.append("resultR <- 'ok'");
        code.addRCode(sb.toString());
    }

    public  class RunRCommand implements Runnable {
        @Override
        public void run(){
            initR();
            caller.runAndReturnResultOnline("resultR");
            String result = "No result";
            try {
                ROutputParser parser = caller.getParser();
                result = RCallerDecodeResult.decodeParser(parser);
            } catch (Exception e) {
                Logger.getLogger(RCallerStuff.class.getName()).log(Level.SEVERE, e.getMessage());
                e.printStackTrace();
            }
        }
    }
}
```

When I stop the R call,  I get errors such as :
java.lang.InterruptedException: sleep interrupted, 
can not send the source  code to R file due to: java.io.IOException: Stream Closed Maximum number of retries exceeded.

I am not certain that the R process has been cleanly interrupted.

I would be happy to know if there is a simpler and more adequate way to interrupt a RCallerRunOnLine call.
.

**Comment by Kopilov** [comment]
Hello!
https://github.com/Kopilov/RCallerService project does exactly what you want. (I had made some patches in RCaller itself to add timeout support) You can use in as an example or as a solution. Or look the timeout unit test [here](https://github.com/jbytecode/rcaller/blob/f8e4145ac0fb11e73e0db88952f4af13368227af/RCaller/src/test/java/com/github/rcaller/RunOnlineTest.java#L179)

**Comment by Kopilov** [comment]
Firts, try to change `StopRCallerOnline` with `stopRCallerAsync`

**Comment by mullon-ch** [comment]
Thank you. I am in the RCalleService. It seems to answer my question. I will let you know. I find `stopRCallerSync` in the code, but I have no direct way to call it (in the Intellij framework); I should do changes in the Rcaller code, which I prefer not, at the present time; maybe this is because the method is deprecated.

**Comment by Kopilov** [comment]
@mullon-ch are you using the latest (3.0.2) version of RCaller?
If yes, [stopRCallerAsync](https://github.com/jbytecode/rcaller/blob/f8e4145ac0fb11e73e0db88952f4af13368227af/RCaller/src/main/java/com/github/rcaller/rstuff/RCaller.java#L465) method should be available, as well as [stopRCallerOnline](https://github.com/jbytecode/rcaller/blob/f8e4145ac0fb11e73e0db88952f4af13368227af/RCaller/src/main/java/com/github/rcaller/rstuff/RCaller.java#L437).
Methods named with capital letter leaded are deprecated only because their names are in non-Java-standard style.
`stopRCallerOnline` uses R API to stop the process (and supposes that no calculation is running for interacting with REPL) and `stopRCallerAsync` uses system API to kill the process.

**Comment by mullon-ch** [comment]
Dear Alexandr,

 t
Thank you very much for your support and your explanations. It is very
clear now and I have almost completed my code; the problems I still have
are due to the subtilities of javafx.

Cheers

Christian

Le jeu. 8 avr. 2021 à 10:51, Kopilov Aleksandr ***@***.***> a
écrit :
