### ISSUE TITLE
Faster Data Transfer

### ISSUE THREAD

**Issue by heebtob** [jbytecode/rcaller#59]
The current Data Transfer over Files is very slow and error prone. Especially when there is no efficient signaling mechanism used.
XML as a dataformat is also not ideal for big data due to size overhead and the De-/Serialization time needed.

One of the fastet or maybe the fastet way to do local IPC is over Shared Memory.
It should be very easy to understand because RAM is much faster than a hard disk or even an SSD.

Why not reengineering this part of RCaller to support Shared Memory?

**Comment by jbytecode** [comment]
Hi @heebtob ,

Well, nice idea. RCaller is quite old and XML was the de facto standard for sharing data between platforms (back to early 2010s). 

RCallerOnline type interactions are streamed between running processes, so I think it is fast enough by means of transferring data. However, as you say, XML is expensive in both parsing and transporting.

Please let me correct, is IPC platform independent or special to POSIX?

First things first, your idea is nice, and we can start a new branch for replacing XML with something more efficient in terms of both space and speed.

Of course, We can also plan for the adaptation of other ideas.

@Kopilov

**Comment by Kopilov** [comment]
Hello friends,

My employer is going to make a new forecast system with compounding several programming languages (such as Java/Kotlin — as a kernel structure, R, Matlab and may be others — as data processing functions). We are going to use [Apache Arrow](https://arrow.apache.org/) as main IPC format. Some designing for kernel and Matlab driver was already made but now another project became more blocking.

I hope, I can return to this project in a few months. Any R-related improves would be pulled to original RCaller. Thanks for the motivation.

**Comment by jbytecode** [comment]
@Kopilov many thanks for your reply.
@heebtob have you got time to start a new branch with improvements and possibly a new version? we can discuss the details in each step.

**Comment by Kopilov** [comment]
Hi @jbytecode ,
I have started working on this issue. I also suggest:

- use Java 11 by default (Java 8 package can be built separately or disabled);
- switch from Maven to Gradle.

Do you approve these points?

**Comment by jbytecode** [comment]
Hi @Kopilov 

- Nowadays, the version 11 is the new default, we can upgrade the minimum JDK requirement to 11 if we use any version specific things in RCaller. Do we?
- I am against canceling the build tool and a sharp shift. Can we still support Maven?

**Comment by Kopilov** [comment]
> Nowadays, the version 11 is the new default, we can upgrade the minimum JDK requirement to 11 if we use any version specific things in RCaller. Do we?

We do not today, but we can use something modern and comfortable. I have been using Kotlin last several years, it is much more concise than Java 6-8. Some similar features can be found in Java 11, bay be. I do not want to make RCaller Kotlin-dependent, but I want to learn and use new trends in Java.

> I am against canceling the build tool and a sharp shift. Can we still support Maven?

Yes we can. However Gradle configuration also is more concise. And using Gradle as a build tool still supports using Maven Central for pulling and pushing dependencies out of the box.

**Comment by jbytecode** [comment]
- okay, please add Gradle support, but Maven xml can be still current.
- we can increment the minimum JDK requirement whenever we use JDK 11 dependent future in RCaller.

do you agree with these results?

**Comment by Kopilov** [comment]
@jbytecode yes, sure

**Comment by jbytecode** [comment]
Hi @Kopilov 

I see you are working hard on the new data transfer mechanism. When will you prepare a pull request for this future? 
The most important issue: Do we have any serious performance gains?

Thank you in advance.

**Comment by Kopilov** [comment]
Hi @jbytecode 

I will pause my work for two weeks vacation (from June 7 to June 20). Tomorrow I can PR current state as is and will try to fix as many unit tests with new data transfer as I can in these two days. Just now 14 of them are still not working.

And I still had not tested the performance. In project we have `benchmark` package made by you, may be, it can be used.

**Comment by Kopilov** [comment]
@jbytecode PR https://github.com/jbytecode/rcaller/pull/61 is opened
@heebtob check the performance in your case, please

**Comment by Kopilov** [comment]
@heebtob notice that the library is not released yet, you should build SNAPSHOT version yourself and add optional dependencies (Apache Arrow) as described in the PR #61 .

**Comment by heebtob** [comment]
@Kopilov Many thanks for your contribution!

I'll try to organize some performance test. I don't know if it's possible during your vacation.

I saw that a Unit Test regarding Matrices is failing. I think that the Unit Test has a bug and it should be the way Apache Arrow does it. I noticed this bug a long time ago. After transferring the matrix it was transposed for no reason.

Have a nice holiday!

**Comment by jbytecode** [comment]
@Kopilov thank you for your great effort.
I will have a look at the new functionality whenever I have time.

**Comment by Kopilov** [comment]
Hello guys,
I have passed the original benchmark with parameters `VectorSize = 20000` and `SimCount = 100` on my Linux laptop.

Results with original (XML) data transferring: 
Min | Max | Median
------|-------|--------
1786|2401|1942

Results with new (Arrow) data transferring: 
Min | Max | Median
------|-------|--------
443|1323|468

@heebtob do you have any statistics?

@jbytecode can we close this issue?

**Comment by jbytecode** [comment]
@Kopilov thank you for your great effort.
ofcourse we can now close the issue.

**Comment by Kopilov** [comment]
@heebtob added to the release, enjoy!
