### ISSUE TITLE
R can be called without using the path to R

### ISSUE THREAD

**Issue by TomDePauw** [jbytecode/rcaller#6]
On Linux and Mac we can use R and Rscript from the commandline. No need to specify the path like /usr/bin/R
This way changing between OS does not affect the application.

Checking that the files exists breaks this functionality. Because java does not see executables as files.

this breaks switching between mac and linux:

        File file = new File(RExecutable);
        if (!file.exists()) {
            throw new RExecutableNotFoundException("R Executable " + RExecutable + " not found");
        }

**Comment by paulcurcean** [comment]
doing that, will start a R process in your terminal, but we can't start the R process like this in our library.

**Comment by TomDePauw** [comment]
It works if you remove the !file.exists() check. I think the library is exactly made so you can use it like that. I wrote code to not do the file test and it works for me. Also in previous versions of Rcaller it did not do the file check, so the library used to work like that.

**Comment by paulcurcean** [comment]
but does this change bring an improvement to the library?

**Comment by TomDePauw** [comment]
Its the only way to get the library to work on osx and linux without having to change environment settings. When switching between develop (osx) and build server/production (linux). Also now there is no support for osx in the library.

**Comment by paulcurcean** [comment]
for Linux is working the way it is (I use Linux).
If somebody removes the symbolic link "R", your approach it won't work anymore. 

But if you're positive sure that it will work, make a pull request.
