### ISSUE TITLE
JVM languages

### ISSUE THREAD

**Issue by jbytecode** [jbytecode/rcaller#60]
I created a folder and started to give some examples on using RCaller in other JVM languages (The first example is in Clojure). We can add some usage examples and code snippets about the other JVM languages including Scala and Kotlin. 

I also added a link in README.md section to this documentation.

Here is the example: [RCaller and Clojure](https://github.com/jbytecode/rcaller/blob/master/markdown/clojure.md)

Best.

@Kopilov

**Comment by Kopilov** [comment]
@jbytecode Thanks!

In new version I converted public `ROutputParser` class to interface (may be you can find more backward compatible way for adding new implementation), look [this commit](https://github.com/Kopilov/rcaller/commit/dce1e81c1d8a5aefafe03550f1ffe870dc96aab7). Other changes (expecting JVM 11) should be still compatible.

**Comment by jbytecode** [comment]
many thanks. 

maybe, this can be carried on an other issue @Kopilov
