### ISSUE TITLE
How to call R code from Java using Rcaller method in CentOs8 ?

### ISSUE THREAD

**Issue by VineelaKantamneni** [jbytecode/rcaller#62]
Please explain me with a very simple example how to run R form java using Rcaller ?

**Comment by jbytecode** [comment]
@VineelaKantamneni 
you can have a look at the test here: https://github.com/jbytecode/rcaller/blob/master/RCaller/src/test/java/com/github/rcaller/RCallerTest.java

You can also follow the journal paper here: https://joss.theoj.org/papers/10.21105/joss.02722
