### ISSUE TITLE
Exception when variable names contains '&' character

### ISSUE THREAD

**Issue by basaldella** [jbytecode/rcaller#8]
When a variable name contains an R character and must be returned by ```runAndReturnResult()```, the following exception occours:

```
Exception in thread "main" com.github.rcaller.exception.ParseException: Can not handle R results due to : Can not parse the R output: org.xml.sax.SAXParseException; lineNumber: 4; columnNumber: 3078; The reference to entity "b" must end with the ';' delimiter.
	at com.github.rcaller.rStuff.RCaller.runAndReturnResult(RCaller.java:412)
```

Example: suppose I have a CSV file named ```candidates.csv``` containing a row like:
```
ID,Feature1,Feature2,Feature3
a&b,1,0.01,0.65
```

And a variable named ```model``` in a file called ```model.RData``` to be used with R's ```predict``` function. If I run the following code inside RCaller:
```R
require("nnet")
load("/tmp/model.RData")
predictions <- read.csv("/tmp/candidates.csv",stringsAsFactors = FALSE)
predictions$score <- predict(model,newdata = predictions,type="raw")
```

And try to get the value of  ```predictions``` with ```runAndReturnResult("predictions");```, the aforementioned exception occours.

**Comment by jbytecode** [comment]
This issue is solved in commit 

https://github.com/jbytecode/rcaller/commit/e6f39725a9e8d2b17da0e0d281ca05f5a068c1af

and the test file UTF8Test.java includes a test which is similar to your example:


@Test
    public void VariableNameContainsAndCharacterTest() throws IOException{
        RCode code = new RCode();
        RCaller caller = new RCaller();
        Globals.detect_current_rscript();
        caller.setRscriptExecutable(Globals.Rscript_current);

        caller.setRCode(code);
        
        TempFileService tmpservice = new TempFileService();
        File tmpfile = tmpservice.createTempFile("csv", "");
        
        BufferedWriter writer = new BufferedWriter(new FileWriter(tmpfile));
        writer.write("ID,Feature1,Feature2,Feature3\n");
        writer.write("a&b,1,0.01,0.65\n");
        writer.flush();
        writer.close();
        
        code.addRCode("predictions <- read.csv(\""+tmpfile.toString()+"\",stringsAsFactors = FALSE)");
        caller.runAndReturnResult("predictions");
        
        String[] result = caller.getParser().getAsStringArray("ID");
        assertEquals("a&b", result[0]);
    }


and the new commit passes all other tests.

**Comment by basaldella** [comment]
Yes, I tested and it on my code and works fine. Small question: when will 2.9 be uploaded to Maven central? 

Thanks for the quick fix!

**Comment by jbytecode** [comment]
Ok @basaldella , we can close the issue then. 

The version 2.9 will not be uploaded, we plan to jump to revision 3.0 because we add remarkable changes to RCaller, including the javax.script support in which the Java community can perform R jobs in a way similar to calling other scripting languages such as Javascript, python, etc. by means of passing data from R to Java and vice versa. Version 3.0 will be uploaded when we finish the major changes and all the tests are passed.

Best wishes.

CC: @paulcurcean
